### PR TITLE
Update for 2.206

### PR DESCRIPTION
**Pull request by Elip100**

### CODE REVIEW

**Comment by Octostomp** [comment]
Could you make a release compiled into the .geode format so I can download and test it

**Comment by CoderQCYT** [comment]
oh i forgot about this project ima do some work

**Comment by Elip100** [comment]
> Could you make a release compiled into the .geode format so I can download and test it

Here is a compiled version. Extract the .geode file and put it into your mods folder.
[gdswearfilter.zip](https://github.com/user-attachments/files/17122059/gdswearfilter.zip)

**Comment by Octostomp** [comment]
> > Could you make a release compiled into the .geode format so I can download and test it
> 
> Here is a compiled version. Extract the .geode file and put it into your mods folder. [gdswearfilter.zip](https://github.com/user-attachments/files/17122059/gdswearfilter.zip)

Only saw this now. It seems to work (although the filter may not be as strict as it was)

**Pull request merged**
